### ISSUE TITLE
Cox login process has changed, breaking component

### ISSUE THREAD

**Issue by jcollas** [ShoGinn/coxdatausage#2]
Looks like the Cox login sequence has recently changed, and redirects to new location.

**Comment by ShoGinn** [comment]
Thanks for the issue report; unfortunately I no longer use Cox so I have no way of checking. I will be archiving this repository and I hope someone can refresh it! ;) maybe even you! The code is fairly easy.

**Comment by jcollas** [comment]
I'm happy to fork it and get it running again.  Thanks for a useful component.  I'll probably get it added to HACS.
